//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FridgeHelper.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.OwnFridges = new HashSet<OwnFridges>();
        }
        [DisplayName("帳號")]
        [Required(ErrorMessage = "請輸入帳號")]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "帳號長度請介於6到15之間")]
        public string account { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "請輸入密碼")]

        public string password { get; set; }

        [DisplayName("姓名")]
        [StringLength(10, ErrorMessage = "最多十字元")]
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnFridges> OwnFridges { get; set; }
    }
}
